Survey Monkey/force-app/main/default/objects/Answer__c/Answer__c.object-meta.xml
<CustomObject>
    <label>Answer</label>
    <nameField>
        <label>Answer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Survey Monkey/force-app/main/default/objects/Answer__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>Position</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Survey Monkey/force-app/main/default/objects/Answer__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Answers</relationshipLabel>
    <relationshipName>Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

Survey Monkey/force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Survey Monkey/force-app/main/default/objects/Question__c/fields/Template__c.field-meta.xml
<CustomField>
    <fullName>Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Template</label>
    <referenceTo>Template__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

Survey Monkey/force-app/main/default/objects/Template__c/Template__c.object-meta.xml
<CustomObject>
    <label>Template</label>
    <nameField>
        <label>Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Survey Monkey/force-app/main/default/classes/getQuestions.cls
public with sharing class getQuestions {
    @AuraEnabled(cacheable=true)
    public static List<Question__c> getQuestionList(ID Id) {
        //DML Check
        dmlManager.checkAccess(new Map<String, Map<String, Set<String>>> {
            'Question__c' => new Map<String, Set<String>> {
                'Read' => new Set<String> {
                    'ID',
                    'Name',
                    'Position__c',
                    'Template__c'
                }
            },
            'Answer__c' => new Map<String, Set<String>> {
                'Read' => new Set<String> {
                    'ID',
                    'Name',
                    'Position__c',
                    'Question__c'
                }
            }
        });
        return [
            SELECT ID, Name, Position__c,
            (
                SELECT ID, Name, Position__c
                FROM Answers__r
                ORDER BY Position__c
            )
            FROM Question__c
            WHERE Template__r.ID = :Id
            ORDER BY Position__c
        ];
    }
}