Survey Monkey/force-app/main/default/objects/Answer__c/Answer__c.object-meta.xml
<CustomObject>
    <label>Answer</label>
    <nameField>
        <label>Answer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Survey Monkey/force-app/main/default/objects/Answer__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>Position</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Survey Monkey/force-app/main/default/objects/Answer__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Answers</relationshipLabel>
    <relationshipName>Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

Survey Monkey/force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Survey Monkey/force-app/main/default/objects/Question__c/fields/Template__c.field-meta.xml
<CustomField>
    <fullName>Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Template</label>
    <referenceTo>Template__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

Survey Monkey/force-app/main/default/objects/Template__c/Template__c.object-meta.xml
<CustomObject>
    <label>Template</label>
    <nameField>
        <label>Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Survey Monkey/force-app/main/default/objects/User_Answer__c/User_Answer__c.object-meta.xml
<CustomObject>
    <label>User Answer</label>
    <nameField>
        <label>User Answer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Answers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Survey Monkey/force-app/main/default/objects/User_Answer__c/fields/Answer__c.field-meta.xml
<CustomField>
    <fullName>Answer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Answer</label>
    <referenceTo>Answer__c</referenceTo>
    <relationshipLabel>User Answers</relationshipLabel>
    <relationshipName>User_Answers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Survey Monkey/force-app/main/default/objects/User_Answer__c/fields/AnswerName__c.field-meta.xml
<CustomField>
    <fullName>AnswerName__c</fullName>
    <label>AnswerName</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Survey Monkey/force-app/main/default/objects/User_Answer__c/fields/AnswerPosition__c.field-meta.xml
<CustomField>
    <fullName>AnswerPosition__c</fullName>
    <label>AnswerPosition</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Survey Monkey/force-app/main/default/objects/User_Answer__c/fields/Checked__c.field-meta.xml
<CustomField>
    <fullName>Checked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Checked</label>
    <type>Checkbox</type>
</CustomField>

Survey Monkey/force-app/main/default/objects/User_Answer__c/fields/QuestionName__c.field-meta.xml
<CustomField>
    <fullName>QuestionName__c</fullName>
    <label>QuestionName</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Survey Monkey/force-app/main/default/objects/User_Answer__c/fields/QuestionPosition__c.field-meta.xml
<CustomField>
    <fullName>QuestionPosition__c</fullName>
    <label>QuestionPosition</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Survey Monkey/force-app/main/default/objects/User_Answer__c/fields/User_Survey__c.field-meta.xml
<CustomField>
    <fullName>User_Survey__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>User Survey</label>
    <referenceTo>User_Survey__c</referenceTo>
    <relationshipLabel>User Answers</relationshipLabel>
    <relationshipName>User_Answers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

Survey Monkey/force-app/main/default/objects/User_Survey__c/User_Survey__c.object-meta.xml
<CustomObject>
    <label>User Survey</label>
    <nameField>
        <label>User Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Survey Monkey/force-app/main/default/objects/User_Survey__c/fields/Template__c.field-meta.xml
<CustomField>
    <fullName>Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Template</label>
    <referenceTo>Template__c</referenceTo>
    <relationshipLabel>User Surveys</relationshipLabel>
    <relationshipName>User_Surveys</relationshipName>
    <type>Lookup</type>
</CustomField>

Survey Monkey/force-app/main/default/objects/User_Survey__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>User_Surveys</relationshipName>
    <type>Lookup</type>
</CustomField>

Survey Monkey/force-app/main/default/classes/getSurveysTests.cls
@isTest 
public class getSurveysTests {

    @isTest static void testGetSurveys() {
        User user = [SELECT ID, Name FROM User WHERE Name = 'Andy Dugan'];
        Template__c template = new Template__c(
            Name = 'Test Template'
        );
        insert template;
        Question__c question = new Question__c(
            Name = 'Test Question',
            Position__c = 1,
            Template__c = template.ID
        );
        insert question;
        Answer__c answer = new Answer__c(
            Name = 'Test Answer',
            Position__c = 1,
            Question__c = question.ID
        );
        insert answer;
        User_Survey__c userSurvey = new User_Survey__c (
            Name = template.Name,
            Template__c = template.ID,
            User__c = user.ID
        );
        insert userSurvey;
        User_Answer__c userAnswer = new User_Answer__c(
            Name = answer.Name,
            User_Survey__c = userSurvey.ID,
            Answer__c = answer.ID,
            Checked__c = true,
            QuestionPosition__c = question.Position__c,
            QuestionName__c = question.Name,
            AnswerPosition__c = answer.Position__c,
            AnswerName__c = answer.Name,
            Id = null
        );
        insert userAnswer;

        List<Map<String, Object>> questionList = new List<Map<String, Object>>();
        Map<String, Object> questions = new Map<String, Object>();
        questions.put('name', question.Name);
        questions.put('position', question.Position__c);
        questions.put('answers', userAnswer.AnswerName__c);
        questionList.add(questions);

        List<Map<String, Object>> correctList = new List<Map<String, Object>>();
        Map<String, Object> correctSurvey = new Map<String, Object>();
        correctSurvey.put('Id', userSurvey.ID);
        correctSurvey.put('name', userSurvey.Name);
        //Change to todays date
        correctSurvey.put('date', null);
        correctSurvey.put('questions', questionList);
        correctList.add(correctSurvey);
        
        //Results
        List<Map<String, Object>> results = getSurveys.getSurveyList(user.ID);
        for(Map<String, Object> indvSurvey : results) {
            indvSurvey.put('date', null);
        }
        System.assertEquals(correctList, results);
    }
}