Survey Monkey/force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Survey Monkey/force-app/main/default/objects/Question__c/fields/Template__c.field-meta.xml
<CustomField>
    <fullName>Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Template</label>
    <referenceTo>Template__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

Survey Monkey/force-app/main/default/objects/Template__c/Template__c.object-meta.xml
<CustomObject>
    <label>Template</label>
    <nameField>
        <label>Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Survey Monkey/force-app/main/default/classes/getQuestionsTests.cls
@isTest 
public class getQuestionsTests {

    @isTest static void testGetAllQuestions() {
        Template__c template = new Template__c(
            Name = 'Test Template'
        );
        insert template;
        Question__c question = new Question__c(
            Name = 'Test Question',
            Position__c = 1,
            Template__c = template.ID
        );
        insert question;

        Map<String, Object> correctQuestion = new Map<String, Object>();
        correctQuestion.put('Name', question.Name);
        correctQuestion.put('Position', question.Position__c);
        correctQuestion.put('ID', question.ID);

        List<Question__c> results = getQuestions.getQuestionList(template.ID);
        Question__c result = results.get(0);

        Map<String, Object> resultQuestion = new Map<String, Object>();
        resultQuestion.put('Name', result.Name);
        resultQuestion.put('Position', result.Position__c);
        resultQuestion.put('ID', result.ID);

        System.assertEquals(correctQuestion, resultQuestion);
    }
}